[project]
name = "aoc-2024"
version = "1.0.0"
description = "Python solutions for AdventOfCode 2024"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "requests",
    "beautifulsoup4",
    "markdownify",
    "pylint",
    "pytest",
    "black",
]
